/** Autogenerated Main.cpp. */

// ==============================| Include only the DSP files  |==============================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// ========================| Now we can add the rest of the codebase |========================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// ====================================| Project Factory |====================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations ---------------------------------------------------------------
		
		registerPolyNode<project::Env25<1>, project::Env25<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::FilterNew<1>, project::FilterNew<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::modtest1<1>, project::modtest1<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::p1<1>, project::p1<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::Pitches<1>, project::Pitches<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::xfade1<1>, project::xfade1<NUM_POLYPHONIC_VOICES>>();
		registerDataNode<project::polymod_networkdata>();
		registerDataNode<project::Averb_networkdata>();
		registerDataNode<project::CableText1_networkdata>();
		registerDataNode<project::cbtes_networkdata>();
		registerDataNode<project::Cho_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::DelaySliders_networkdata>();
		registerDataNode<project::dist3_networkdata>();
		registerDataNode<project::dist4_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::env_networkdata>();
		registerDataNode<project::eventin_networkdata>();
		registerDataNode<project::EventOut_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::finalgain_networkdata>();
		registerDataNode<project::Fm_networkdata>();
		registerDataNode<project::FoldTests_networkdata>();
		registerDataNode<project::glide_networkdata>();
		registerDataNode<project::menv_networkdata>();
		registerDataNode<project::Mod1_networkdata>();
		registerDataNode<project::modsz_networkdata>();
		registerDataNode<project::modtest2_networkdata>();
		registerDataNode<project::ModToCable_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::pan1_networkdata>();
		registerDataNode<project::pan2_networkdata>();
		registerDataNode<project::pan3_networkdata>();
		registerDataNode<project::pan4_networkdata>();
		registerDataNode<project::pan5_networkdata>();
		registerDataNode<project::pan6_networkdata>();
		registerDataNode<project::pan7_networkdata>();
		registerDataNode<project::pan8_networkdata>();
		registerDataNode<project::PanSliders_networkdata>();
		registerDataNode<project::PanSliders2_networkdata>();
		registerDataNode<project::Pitch_networkdata>();
		registerDataNode<project::PitchMod_networkdata>();
		registerDataNode<project::PitchModB_networkdata>();
		registerDataNode<project::PitchNu1_networkdata>();
		registerDataNode<project::PitchNu2_networkdata>();
		registerDataNode<project::PitchNu3_networkdata>();
		registerDataNode<project::PitchNu4_networkdata>();
		registerDataNode<project::PitchNu5_networkdata>();
		registerDataNode<project::PitchNu6_networkdata>();
		registerDataNode<project::PitchNu7_networkdata>();
		registerDataNode<project::PitchNu8_networkdata>();
		registerDataNode<project::PitchSliders_networkdata>();
		registerDataNode<project::PitchStage1_networkdata>();
		registerDataNode<project::PitchStage2_networkdata>();
		registerDataNode<project::PitchStage3_networkdata>();
		registerDataNode<project::PitchStage4_networkdata>();
		registerDataNode<project::PitchStage5_networkdata>();
		registerDataNode<project::PitchStage6_networkdata>();
		registerDataNode<project::PitchStage7_networkdata>();
		registerDataNode<project::PitchStage8_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::PitchTop_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::PreGain_networkdata>();
		registerDataNode<project::PreSliders2_networkdata>();
		registerDataNode<project::recdel_networkdata>();
		registerDataNode<project::RevDel_networkdata>();
		registerDataNode<project::ScrubOSc_networkdata>();
		registerDataNode<project::snextext_networkdata>();
		registerDataNode<project::StageDelay_networkdata>();
		registerDataNode<project::TrigRouting_networkdata>();
		registerDataNode<project::Vector1_networkdata>();
		registerDataNode<project::VoiceKill_networkdata>();
		registerDataNode<project::WaveGuide_networkdata>();
		registerDataNode<project::WaveGuide2_networkdata>();
		registerDataNode<project::WtMod1_networkdata>();
		registerDataNode<project::WtMod2_networkdata>();
		registerDataNode<project::WtSliders_networkdata>();
		registerDataNode<project::Xf1Input1_networkdata>();
		registerDataNode<project::xfade_networkdata>();
		registerDataNode<project::xfade2_networkdata>();
		registerDataNode<project::_8Delay_networkdata>();
		registerDataNode<project::_8sine_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


