/** Autogenerated Main.cpp. */

// ==============================| Include only the DSP files  |==============================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// ========================| Now we can add the rest of the codebase |========================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// ====================================| Project Factory |====================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations ---------------------------------------------------------------
		
		registerPolyNode<project::chain26<1>, project::chain26<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::FilterNew<1>, project::FilterNew<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::Mod1<1>, project::Mod1<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::modtest1<1>, wrap::illegal_poly<project::modtest1<1>>>();
		registerPolyNode<project::p1<1>, project::p1<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::pan<1>, project::pan<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::xfade1<1>, project::xfade1<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::xfade2<1>, project::xfade2<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::xfade3<1>, project::xfade3<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::xfade4<1>, project::xfade4<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::xfade5<1>, project::xfade5<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::xfade6<1>, project::xfade6<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::xfade7<1>, project::xfade7<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::xfade8<1>, project::xfade8<NUM_POLYPHONIC_VOICES>>();
		registerDataNode<project::polymod_networkdata>();
		registerDataNode<project::Averb_networkdata>();
		registerDataNode<project::CableText1_networkdata>();
		registerDataNode<project::cbtes_networkdata>();
		registerDataNode<project::Cho_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::eventin_networkdata>();
		registerDataNode<project::EventOut_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::finalgain_networkdata>();
		registerDataNode<project::Fm_networkdata>();
		registerDataNode<project::FoldTests_networkdata>();
		registerDataNode<project::glide_networkdata>();
		registerDataNode<project::ModToCable_networkdata>();
		registerDataNode<project::mtest_networkdata>();
		registerDataNode<project::PanSliders_networkdata>();
		registerDataNode<project::PanSliders2_networkdata>();
		registerDataNode<project::PitchMod_networkdata>();
		registerDataNode<project::PitchNu1_networkdata>();
		registerDataNode<project::PitchNu2_networkdata>();
		registerDataNode<project::PitchNu3_networkdata>();
		registerDataNode<project::PitchNu4_networkdata>();
		registerDataNode<project::PitchNu5_networkdata>();
		registerDataNode<project::PitchNu6_networkdata>();
		registerDataNode<project::PitchNu7_networkdata>();
		registerDataNode<project::PitchNu8_networkdata>();
		registerDataNode<project::PitchSliders_networkdata>();
		registerDataNode<project::PitchStage1_networkdata>();
		registerDataNode<project::PitchStage2_networkdata>();
		registerDataNode<project::PitchStage3_networkdata>();
		registerDataNode<project::PitchStage4_networkdata>();
		registerDataNode<project::PitchStage5_networkdata>();
		registerDataNode<project::PitchStage6_networkdata>();
		registerDataNode<project::PitchStage7_networkdata>();
		registerDataNode<project::PitchStage8_networkdata>();
		registerDataNode<project::PitchTop_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::PreGain_networkdata>();
		registerDataNode<project::PreSliders2_networkdata>();
		registerDataNode<project::WtMod1_networkdata>();
		registerDataNode<project::xfade_networkdata>();
		registerDataNode<project::_8Delay_networkdata>();
		registerDataNode<project::_8sine_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


