namespace project
{

struct filter_networkdata: public scriptnode::dll::InterpretedNetworkData
{
	String getId() const override
	{
		return "filter";
	}
	bool isModNode() const override
	{
		return false;
	}
	String getNetworkData() const override
	{
		return "787.nT6K8C1BNzDF.XWGcYB7Lqd.PkfKXhV7JQDZlxooapeZAQlfv00FAzjy.O+T4IsyTxXxTDE.QAvT.XUXq+8w7pqAC+Deq0y1lvZrbp+7xuSpUOfi0b8D1pzqkWggi+HEAmie8BGacMoZx1jzDhfJkRXmm1gimzKa8Wfq+UdkoAvwTrrvwapzHtOBAzNleFzLbrDebZw4Xa8yjQaxlKyrWT7qSQhWlgQOf4WS5KzNXnik0Mbbzh0OmzCb22gpqvjdccoVjdYgy4qLCRuApzgNfEwOJoUJHRwZHLbLG7avz39wGQJFDyuA3y1t7S58dpfdOuBfZ6WgL+In0JNWq+AZMiY1FiR5dSlcckZWZHMXr3pY08jGJbjzp.70wnWMITr7l3BS1ewH85FR3W31MutD7KBBmdppllhLAmfnjfhh7fNRSMAMq.9nfTTUvWjmHoG2TPPonnIJ3TEUTzKhZBJ5IUUAQAY8W904kesZ19ga8w1wFK+d8HvHQPHoGkzaRZpJh.XpfFcqYngjY.B.DPR.PA.PF6nZ6jAbjZnPy+obneeX.CzmTn2nXIaEleycTqt6nYmcXRTvHno2f1oXT8PGyz9.oOVlzt+HoHisrb7R1IvMpVnIlgtKcN5n3QWe4EPcC4nlIiyTQlN0gMRUPzbYjpTHctELDHDNLSNcDROr2HbTkBywZFdPQNJymDH6sIkDJCMPLQfbhXrxbETAvlInku1rw.wBMzAKL91Q+HYTfiYkabGGfHQFl04BC5DN7Y8AO9Qv5AH6oTe2HIBf.JpdIOIYoQL.FNseFrkA3prbxNq7aS3tPJymDbNyRjeUYYUsgBeXCAvuvgiAj.FW+kZLYCGAIcX81D7dVjLshcgDS2vtURz1K.58Y0y35CK.VlxxTaB7pNPkDCdyN+hj.C65FBKZD1OvOtKgImPUFaBCMPSFxImQAAfMIbMzDTlIeOusKoiwT5Td9xPrWa3Qr3tsDlqVVZNfylXK+rtPzlQ4rsvfH3AYMzsSIDvfLOsoMFBSfvl6VlyJMghABh263SWG3lA3wC";
	}
};
}

