namespace project
{

struct FMOUT2_networkdata: public scriptnode::dll::InterpretedNetworkData
{
	String getId() const override
	{
		return "FMOUT2";
	}
	bool isModNode() const override
	{
		return false;
	}
	String getNetworkData() const override
	{
		return "631.nT6K8CFCGz1D.XBGZUB7PaFjCoDXjaNO7SsxK3z09srJ09uTcJWIfEoFIhG8QYi0ebR+OAfS.DE.QbOfFCPqcZdLVhk4P24R590oLWsWtAstSVhI6ZyWRKNZ8qwFQq0RNOfVWsS78snetiVeMq1NXYTKlPVJsgFRQERbwhCo0UfvQq8bsgxeDkoeSdOWj54dHH.zih5KdzaiYFrOmgRC4k1a8ChJsnNu3sNJ+ejWIlteL3OZsFulJDsViu+lMfbHSRwvyJsV2xrrhFOE6ikhzekT57Ba8bw.PqopbSVPpKHK0RQhSclAYutBOEC40ETIFVJGufG0IV1AyiOKe30sclkSrPjIOO508TrBFiuoJI+frq5CJi+ZwGPhUkE0DDNQBkKFgvPumz37i+I7Hc2Iasex7bUQJqXbx8bSOGRzM8nrnppbUPHjRRhefChiVcJ4.+rw8oIqDzTeLAC3Q9XdT2RprlDqbRrHnUsy70WqVJYy78wrAzFnwTTgTxLBFEf.HHf.fQ.fHirNPc3gqgv7gglJiIxnIP.QlrIhAXjFkyxXVxQYo8PW4YRjnqLBlo.VIhRR9HhcvyG5Yx4vFXAsnVLOkCHfwnQrCTkCHKiuKXb7hMmYY616.m9kQ8twBfqzJ3ywhvMPlRP6ABtgYADXFlvLzwVPypD8rKKaObGejZrJA1DqX.5vAOlnXeosHULLwWLXeKMJUhDvI6tT6s9djpSfdDqwAHJ4jpF7BoC1ShC+FrX.2INjG.JfKiRCFVFy1GfkgKaPAFdoA5f5ooHTjxR2GzqvbdtDEtI3EvLvXjCWdaBh2HPswSV1.1y0r1Sbnz4Avy.92A";
	}
};
}

