/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include compiled network files ------------------

#include "arrange_networkdata.h"
#include "CLEAR_networkdata.h"
#include "clonetest.h"
#include "cmod_networkdata.h"
#include "ctest2.h"
#include "DUALFILTER_networkdata.h"
#include "env_networkdata.h"
#include "file_networkdata.h"
#include "FilterVCA_networkdata.h"
#include "fold_networkdata.h"
#include "gate.h"
#include "gater_networkdata.h"
#include "harmFMnode_networkdata.h"
#include "harmnode2_networkdata.h"
#include "harmnode_networkdata.h"
#include "harmo2_networkdata.h"
#include "HarmOct_networkdata.h"
#include "Harmonic_networkdata.h"
#include "harmo_networkdata.h"
#include "harmx4node_networkdata.h"
#include "harmx8node_networkdata.h"
#include "Harrage_networkdata.h"
#include "Hclone16_networkdata.h"
#include "Hclone32_networkdata.h"
#include "Hclone4_networkdata.h"
#include "Hclone8_networkdata.h"
#include "H_Arrange_networkdata.h"
#include "LFO_networkdata.h"
#include "main_networkdata.h"
#include "MidiNote_networkdata.h"
#include "MidiVel_networkdata.h"
#include "MOD1CABLE_networkdata.h"
#include "modsel_networkdata.h"
#include "modswitcher_networkdata.h"
#include "modtest_networkdata.h"
#include "mod_networkdata.h"
#include "Osc_networkdata.h"
#include "pmod_networkdata.h"
#include "polymod.h"
#include "polymod2_networkdata.h"
#include "polymod3_networkdata.h"
#include "polymod4_networkdata.h"
#include "SampleFM_networkdata.h"
#include "test_networkdata.h"
#include "timer_networkdata.h"
#include "time_networkdata.h"
#include "t_networkdata.h"
#include "xfadeswitch_networkdata.h"
#include "XFADEx8_networkdata.h"
#include "_4wayswitch_networkdata.h"
#include "_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

