/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "custom_node.h"

// Include compiled network files ------------------

#include "Arranged_networkdata.h"
#include "fff_networkdata.h"
#include "gran_networkdata.h"
#include "Midis_networkdata.h"
#include "MidiTrack.h"
#include "MidiVel.h"
#include "modroutePitch_networkdata.h"
#include "modrouteVol_networkdata.h"
#include "modroute_networkdata.h"
#include "pmod_networkdata.h"
#include "polymod3_networkdata.h"
#include "polymod_networkdata.h"
#include "Switcher_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

