/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "custom_node.h"

// Include compiled network files ------------------

#include "Arranged_networkdata.h"
#include "DspNetwork_networkdata.h"
#include "HarmFade.h"
#include "Midis_networkdata.h"
#include "MidiTrack.h"
#include "MidiVel.h"
#include "modroutePitch_networkdata.h"
#include "modroute_networkdata.h"
#include "MutiChorus_networkdata.h"
#include "pmod_networkdata.h"
#include "polymod.h"
#include "polymod2_networkdata.h"
#include "polymod3_networkdata.h"
#include "polymod4_networkdata.h"
#include "scales_networkdata.h"
#include "XFHarm.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

