namespace project
{

struct ModToCable_networkdata: public scriptnode::dll::InterpretedNetworkData
{
	String getId() const override
	{
		return "ModToCable";
	}
	bool isModNode() const override
	{
		return false;
	}
	String getNetworkData() const override
	{
		return "784.nT6K8C1YwTCF.XHWZUB.QhFCmxXaCH1i+Q9AsObJzzfgLJrzjjcSaFf2kizsOr.4vrxePA.T.3D.QbPny0pKLGjFyo8V9k9wAPqodLL+ZSDss5XLIA+1pms2IWBsFiriYC9lmbIdz5m5do0ZIONHs1dqX3mh9qpvmbmf5ZwEo0Tp3z5Lv2Mx+k.GtEmqYqVbsteO3dzZNdJakVqwvuEVjEwFu5BqRwyNEN9pKq6jt+rJmBGD7meKG6XlLn0TUldq8NI+Wf8Ir2Z1qxntV.nI4wTWKMUdE2pKbAAAAMoTJkJmy4bNiRoTJgxXLFiuHDBgvmGDHTTNeuCdE7Dnyt0MmAwCoM0L9utXLNslFMkfRvHnDmcqtSjbgslytXWCt90QMy0myPet.FMglPPSHIURoRZbFmy37Y9.kPoDJewWL9hvmGBP3y.PomzagWDo.dhRZTTiMUydNiSf7sJii.mHmlC3mxerFO6TZx1Wi2o.CUppkifHJEJfFiZ73NBfA.Hf.DPCvCf.YJLB.HDNXbP.PbPDfAfQ.CBF..CA.HDfP.E.ACHbFfQC2CNPEVr9O1oXpPpWYVB+.2nfTbZUMlkiz4qvHEgRofpEweZ8yXsBmJnPUsrrsrefAJFJjpUeqzTAaYDB3trB1sX8sRYVaqkUKOVBQMdAKVB11gUbl8zK.zG5MD5Ju3ZywTMryN3pACrGJuXJS62Cjvd9dN+0fp7oXXaT.1YCdcCEF4aSN4vHEIYQyIUtvlI5Wn.elwQjY3msnYWj.jEvfEn1dgCUSFgc6PMtnxHKvIahx4HNGQlgc1h14QLNhrC6rRDsX7WMIiQhQtcstfxFVpYkvTeY+fQ7BkwyHrmyBCA6uZvDCjJouC6PUsfC2AtmYzQRPAHCWDYqwUTRPTA6aUKumSpnZkrFHXepG6Wd3LdXneVPNwdBZ9GnRsB9zxwSAr3JI6hQcWvvwvj0O7mxHix6u+YR.gUER70C.dtf3MnBml2.4Oz9beYWOqRiK2n3+4v4s3JdkGkG6ClSmcibB481oYXoQS8zA.";
	}
};
}

