var Sys101External = ["101Ext_Bell1", "101Ext_Bell2", "101Ext_Bell3", "101Ext_Bell4", "101Ext_Vox1", "101Ext_Vox2", "101Ext_Vox3", "101Ext_Vox4", "101Ext_Vox5", "101Ext_Vox6", "101Ext_Vox7", "101Ext_Vox8"];

var Sys101Noise = ["101Noise_Pink1", "101Noise_Pink2", "101Noise_Pink3", "101Noise_Pink4", "101Noise_Pink5", "101Noise_Pink6", "101Noise_Pink7", "101Noise_Pink8"];

var Sys101Saw = ["101Saw_HiRes1", "101Saw_HiRes2", "101Saw_HiRes3", "101Saw_HiRes4", "101Saw_HiRes5", "101Saw_HiRes6", "101Saw_HiRes7", "101Saw_HiRes8", "101Saw_MidRes1", "101Saw_MidRes2", "101Saw_MidRes3", "101Saw_MidRes4", "101Saw_MidRes5", "101Saw_MidRes6", "101Saw_MidRes7", "101Saw_MidRes8"];

var Sys101Square = ["101Sqr_HiRes1", "101Sqr_HiRes2", "101Sqr_HiRes3", "101Sqr_HiRes4", "101Sqr_HiRes5", "101Sqr_HiRes6", "101Sqr_HiRes7", "101Sqr_HiRes8", "101Sqr_MidRes1", "101Sqr_MidRes2", "101Sqr_MidRes3", "101Sqr_MidRes4", "101Sqr_MidRes5", "101Sqr_MidRes6", "101Sqr_MidRes7", "101Sqr_MidRes8"];

var Sys101Triangle = [ "101Tri_HiRes1", "101Tri_HiRes2", "101Tri_HiRes3", "101Tri_HiRes4", "101Tri_HiRes5", "101Tri_HiRes6", "101Tri_HiRes7", "101Tri_HiRes8", "101Tri_MidRes1", "101Tri_MidRes2", "101Tri_MidRes3", "101Tri_MidRes4", "101Tri_MidRes5", "101Tri_MidRes6", "101Tri_MidRes7", "101Tri_MidRes8"];

var CS30 = ["CSBass_Bz", "CSBass_Grizzle", "CSBass_RM", "CSBass_k30l2", "CSFX_Crunch", "CSFX_Devistate", "CSFX_FeedFwd", "CSFX_Rust", "CSKeys_Bargain", "CSKeys_Toes", "CSLead_Astonish", "CSLead_Day3", "CSLead_FakeSync", "CSLead_HiYearner", "CSLead_Messin", "CSLead_Sayer", "CSLead_Scream", "CSLead_Simple", "CSLead_k30l", "CSPad_Brew", "CSPad_Cream", "CSPad_Drama", "CSPad_LickElectric", "CSPad_LoopAx", "CSStrings_Maybe"];

var CSWaves = ["CSWave_Noise", "CSWave_Pulse1", "CSWave_Pulse2", "CSWave_Pulse3", "CSWave_Pulse4", "CSWave_Pulse5", "CSWave_Saw", "CSWave_Sine"];

var K3 = ["K3Bass_Double", "K3Bass_Shrp", "K3Bass_Slap", "K3Bass_eBass", "K3Bass_hard", "K3Bell_Belle", "K3Bell_More", "K3Bell_Src", "K3FX_Zap", "K3Keys_Darkly", "K3Keys_Euro", "K3Keys_Odd", "K3Keys_Swish1", "K3Keys_Swish2", "K3Keys_Swish3", "K3Keys_Swish4", "K3Keys_Swoosh1", "K3Keys_Swoosh2", "K3Keys_Swoosh3", "K3Lead_Egg", "K3Lead_SadRing", "K3Lead_SlwRing1", "K3Lead_SlwRing2", "K3Lead_SlwRing3", "K3Lead_Tinkle", "K3Pad_1st", "K3Pad_Lingo", "K3Pad_Rouse", "K3Pad_Special", "K3Pad_Trouble", "K3Pluck_Gater"];

var ModFM = ["ModFM_AMFM1", "ModFM_AMFM2", "ModFM_AMFM3", "ModFM_AMFM4", "ModFM_AMFM5", "ModFM_AMFM6", "ModFM_AMFM7", "ModFM_AMFM8", "ModFM_FoldSweep1", "ModFM_FoldSweep2", "ModFM_FoldSweep3", "ModFM_FoldSweep4", "ModFM_FoldSweep5", "ModFM_FoldSweep6", "ModFM_FoldSweep7", "ModFM_FoldSweep8"];

var ModFiltered = ["ModFiltered_BpSweep1", "ModFiltered_BpSweep2", "ModFiltered_BpSweep3", "ModFiltered_BpSweep4", "ModFiltered_BpSweep5", "ModFiltered_BpSweep6", "ModFiltered_DfNotch1", "ModFiltered_DfNotch2", "ModFiltered_DfNotch3", "ModFiltered_DfNotch4", "ModFiltered_DfNotch5", "ModFiltered_DfNotch6", "ModFiltered_DfNotch7", "ModFiltered_DfNotch8", "ModFiltered_FFM1", "ModFiltered_FFM2", "ModFiltered_FFM3", "ModFiltered_FFM4", "ModFiltered_FFM5", "ModFiltered_FFM6", "ModFiltered_FFM7", "ModFiltered_FFM8", "ModFiltered_FFMb1", "ModFiltered_FFMb2", "ModFiltered_FFMb3", "ModFiltered_FFMb4", "ModFiltered_FFMb5", "ModFiltered_FFMb7", "ModFiltered_FFMb8", "ModFiltered_LPSqr1", "ModFiltered_LPSqr2", "ModFiltered_LPSqr3", "ModFiltered_LPSqr4", "ModFiltered_LPSqr5", "ModFiltered_LPSqr6", "ModFiltered_LPSqr7", "ModFiltered_LPSqr8", "ModFiltered_Thickly1", "ModFiltered_Thickly2", "ModFiltered_Thickly3", "ModFiltered_Thickly4", "ModFiltered_Thickly5", "ModFiltered_Thickly6", "ModFiltered_Thickly7", "ModFiltered_Thickly8"];

var ModShape = ["ModShape_DfSeq1", "ModShape_DfSeq2", "ModShape_DfSeq3", "ModShape_DfSeq4", "ModShape_DfSeq5", "ModShape_DfSeq6", "ModShape_DfSeq7", "ModShape_DfSeq8", "ModShape_ShpMod1", "ModShape_ShpMod2", "ModShape_ShpMod3", "ModShape_ShpMod4", "ModShape_ShpMod5", "ModShape_ShpMod6", "ModShape_ShpMod7", "ModShape_ShpMod8", "ModShape_ShpModB1", "ModShape_ShpModB2", "ModShape_ShpModB3", "ModShape_ShpModB4", "ModShape_ShpModB5", "ModShape_ShpModB6", "ModShape_ShpModB7", "ModShape_ShpModB8"];

var Stereo = ["ST_Blowy", "ST_Crunchy", "ST_CsShock", "ST_CupCake", "ST_DF1", "ST_DF2", "ST_Gravel", "ST_OgRadio", "ST_OgSly", "ST_Ogdf", "ST_Rav"];

 var XPFM = ["XPFM_fma1", "XPFM_fma2", "XPFM_fma3", "XPFM_fma4", "XPFM_fma5", "XPFM_fma6", "XPFM_fma7", "XPFM_fma8", "XPFM_fmb1", "XPFM_fmb2", "XPFM_fmb3", "XPFM_fmb4", "XPFM_fmb5", "XPFM_fmb6", "XPFM_fmb7", "XPFM_fmb8", "XPFM_fmc1", "XPFM_fmc2", "XPFM_fmc3", "XPFM_fmc4", "XPFM_fmc5", "XPFM_fmc6", "XPFM_fmc7", "XPFM_fmc8"];
 
var XPMisc = ["XPMisc_2finga", "XPMisc_Spiano", "XPMisc_Stack", "XPMisc_VoxLd1", "XPMisc_VoxLd2", "XPMisc_WarmThk1", "XPMisc_WarmThk2", "XPMisc_WarmThk3"];

var XPSaw = ["XPSaw_1PLPa1", "XPSaw_1PLPa2", "XPSaw_1PLPa3", "XPSaw_1PLPa4", "XPSaw_1PLPb1", "XPSaw_1PLPb2", "XPSaw_1PLPb3", "XPSaw_1PLPb4", "XPSaw_1PLPb5", "XPSaw_1PLPb6", "XPSaw_1PLPb7", "XPSaw_1PLPb8", "XPSaw_4PBP1", "XPSaw_4PBP2", "XPSaw_4PBP3", "XPSaw_4PBP4", "XPSaw_4PBP5", "XPSaw_4PBP6", "XPSaw_4PBP7", "XPSaw_4PBP8", "XPSaw_ALT1", "XPSaw_ALT2", "XPSaw_ALT3", "XPSaw_ALT4", "XPSaw_ALT5", "XPSaw_ALT6", "XPSaw_ALT7", "XPSaw_ALT8", "XPSaw_DetuneLP1", "XPSaw_DetuneLP2", "XPSaw_DetuneLP3", "XPSaw_DetuneLP4", "XPSaw_DetuneLP5", "XPSaw_DetuneLP6", "XPSaw_DetuneLP7", "XPSaw_DetuneLP8", "XPSaw_HiLo1", "XPSaw_HiLo2", "XPSaw_HiLo3", "XPSaw_HiLo4", "XPSaw_Lp2p1", "XPSaw_Lp2p2", "XPSaw_Lp2p3", "XPSaw_Lp2p4", "XPSaw_Lp2p5", "XPSaw_Lp2p6", "XPSaw_Lp3p1", "XPSaw_Lp3p2", "XPSaw_Lp3p3", "XPSaw_Lp3p4", "XPSaw_Lp3p5", "XPSaw_Lp3p6", "XPSaw_Lp3p7", "XPSaw_Lp3p8", "XPSaw_NoiseLP1", "XPSaw_NoiseLP2", "XPSaw_NoiseLP3", "XPSaw_NoiseLP4", "XPSaw_Phase1", "XPSaw_Phase2", "XPSaw_Phase3", "XPSaw_Phase4", "XPSaw_Phase5", "XPSaw_Phase6", "XPSaw_Phase7", "XPSaw_Phase8"];

var XPSquare = [ "XPSqr_ALT1", "XPSqr_ALT2", "XPSqr_ALT3", "XPSqr_ALT4", "XPSqr_ALT5", "XPSqr_ALT6", "XPSqr_ALT7", "XPSqr_ALT8", "XPSqr_Hp2p1", "XPSqr_Hp2p2", "XPSqr_Hp2p3", "XPSqr_Hp2p4", "XPSqr_Hp2p5", "XPSqr_Hp2p6", "XPSqr_Hp2p7", "XPSqr_Hp2p8", "XPSqr_Lp3p1", "XPSqr_Lp3p2", "XPSqr_Lp3p3", "XPSqr_Lp3p4", "XPSqr_Lp3p5", "XPSqr_Lp3p6", "XPSqr_Lp3p7", "XPSqr_Lp3p8", "XPSqr_Lp4p1", "XPSqr_Lp4p2", "XPSqr_Lp4p3", "XPSqr_Lp4p4", "XPSqr_Lp4p5", "XPSqr_Lp4p6", "XPSqr_Lp4p7", "XPSqr_Lp4p8", "XPSqr_Omod1", "XPSqr_Omod2", "XPSqr_Omod3", "XPSqr_Omod4", "XPSqr_Omod5", "XPSqr_Omod6", "XPSqr_Omod7", "XPSqr_Omod8", "XPSqr_PW1", "XPSqr_PW2", "XPSqr_PW3", "XPSqr_PW4", "XPSqr_PW5", "XPSqr_PW6", "XPSqr_PW7", "XPSqr_PW8", "XPSqr_PWM1", "XPSqr_PWM2", "XPSqr_PWM3", "XPSqr_PWM4", "XPSqr_PWM5", "XPSqr_PWM6", "XPSqr_PWM7", "XPSqr_PWM8", "XPSqr_Phs1", "XPSqr_Phs2", "XPSqr_Phs3", "XPSqr_Phs4", "XPSqr_Phs5", "XPSqr_Phs6", "XPSqr_Phs7", "XPSqr_Phs8", "XPSqr_PulseDemon1", "XPSqr_PulseDemon2", "XPSqr_PulseDemon3", "XPSqr_PulseDemon4", "XPSqr_PwFiltered1", "XPSqr_PwFiltered2", "XPSqr_PwFiltered3", "XPSqr_PwFiltered4", "XPSqr_PwFiltered5", "XPSqr_PwFiltered6", "XPSqr_PwFiltered7", "XPSqr_PwFiltered8"];

var XPTriangle = ["XPTri_LP2p1", "XPTri_LP2p2", "XPTri_LP2p3", "XPTri_LP2p4", "XPTri_LP2p5", "XPTri_LP2p6", "XPTri_NoiseLP1", "XPTri_NoiseLP2", "XPTri_NoiseLP3", "XPTri_NoiseLP4", "XPTri_NoiseLP5", "XPTri_NoiseLP6", "XPTri_Notch1", "XPTri_Notch2", "XPTri_Notch3", "XPTri_Notch4", "XPTri_Phase1", "XPTri_Phase2", "XPTri_Phase3", "XPTri_Phase4", "XPTri_Phase5", "XPTri_Phase6"];