[
  "Juno::Mid Res Misc 2",
  "Juno::Mid Res Misc 5",
  "Juno::No Res Misc 6",
  "Juno::No Res Misc 1",
  "Juno::No Res Saw 4",
  "Juno::No Res Square 5",
  "Juno::High Res Misc 1",
  "Juno::High Res Square 10",
  "Juno::Mid Res Square 4",
  "Juno::High Res Saw 2",
  "Juno::High Res Noise",
  "Juno::Mid Res Saw 6",
  "Juno::Mid Res Saw 1",
  "Juno::No Res Saw 7",
  "Juno::High Res Misc 4",
  "Juno::High Res Square 8",
  "Juno::High Res Square 1",
  "Juno::No Res Noise",
  "Juno::Mid Res Noise",
  "Juno::High Res Saw 1"
]