/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "b259wf.h"

// Include compiled network files ------------------

#include "eventin_networkdata.h"
#include "EventOut_networkdata.h"
#include "FilterNew2_networkdata.h"
#include "FilterNew3_networkdata.h"
#include "FilterNew4_networkdata.h"
#include "FilterNew5_networkdata.h"
#include "FilterNew6_networkdata.h"
#include "FilterNew7_networkdata.h"
#include "FilterNew8_networkdata.h"
#include "FilterNew_networkdata.h"
#include "finalgain_networkdata.h"
#include "Fold.h"
#include "FoldTests.h"
#include "glide_networkdata.h"
#include "Mod10_networkdata.h"
#include "Mod11_networkdata.h"
#include "Mod12_networkdata.h"
#include "Mod1_networkdata.h"
#include "Mod2_networkdata.h"
#include "Mod3_networkdata.h"
#include "Mod4_networkdata.h"
#include "Mod5_networkdata.h"
#include "Mod9_networkdata.h"
#include "p1_networkdata.h"
#include "p2_networkdata.h"
#include "p3_networkdata.h"
#include "p4_networkdata.h"
#include "p5_networkdata.h"
#include "p6_networkdata.h"
#include "p7_networkdata.h"
#include "p8_networkdata.h"
#include "pan2_networkdata.h"
#include "pan3_networkdata.h"
#include "pan4_networkdata.h"
#include "pan5_networkdata.h"
#include "pan6_networkdata.h"
#include "pan7_networkdata.h"
#include "pan8_networkdata.h"
#include "PanSliders_networkdata.h"
#include "pan_networkdata.h"
#include "PitchMod_networkdata.h"
#include "PitchStage1_networkdata.h"
#include "PitchStage2_networkdata.h"
#include "PitchStage3_networkdata.h"
#include "PitchStage4_networkdata.h"
#include "PitchStage5_networkdata.h"
#include "PitchStage6_networkdata.h"
#include "PitchStage7_networkdata.h"
#include "PitchStage8_networkdata.h"
#include "polymod_networkdata.h"
#include "PreGain_networkdata.h"
#include "xfade1_networkdata.h"
#include "xfade2_networkdata.h"
#include "xfade3_networkdata.h"
#include "xfade4_networkdata.h"
#include "xfade5_networkdata.h"
#include "xfade6_networkdata.h"
#include "xfade7_networkdata.h"
#include "xfade8_networkdata.h"
#include "_8Delay_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

